name: Keep Streamlit App Alive

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  keepalive:
    runs-on: ubuntu-latest

    steps:
      - name: Wake Streamlit
        run: |
          curl -L -A "Mozilla/5.0" https://makevocabpiccard.streamlit.app/ > /dev/null 2>&1
